services:
  redis:
    image: redis:8.0-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379' 
    volumes:
      - redis_data:/data # Mount a named volume for data persistence
    command: redis-server --appendonly yes # Optional: Enable AOF persistence

volumes:
  redis_data:
    driver: local